### ISSUE TITLE
Outset munki recipe causes disco freakout

### ISSUE THREAD

**Issue by arubdesu** [sheagcraig/easy_rider#5]
```py
Making override for outset.munki
Traceback (most recent call last):
  File "./easy_rider.py", line 455, in <module>
    main()
  File "./easy_rider.py", line 168, in main
    process_overrides(recipes, args, production_cat, pkginfo_template)
  File "./easy_rider.py", line 200, in process_overrides
    override = FoundationPlist.readPlist(override_path)
  File "/Users/allister/Downloads/easy_rider-master/FoundationPlist.py", line 85, in readPlist
    raise NSPropertyListSerializationException(errmsg)
FoundationPlist.NSPropertyListSerializationException: stream had too few bytes in file 
```
Same traceback for cdef.munki and OracleJavaJDK.munki

**Comment by arubdesu** [comment]
oh crap, I didn't have those recipes local.. 😅
